spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orcl?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    root: WARN
#    org.springframework.beans: DEBUG
    com.simpleMS.microserv.controller: TRACE
    org.hibernate: DEBUG
server.port: 8080